//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoughaibandco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RouteName { get; set; }
        public Nullable<int> BannersId { get; set; }
        public Nullable<int> Order { get; set; }
        public string Side { get; set; }
        public string BackgroundImage { get; set; }
        public string ForegroundImage { get; set; }
        public bool IsAdminAdded { get; set; }
        public string PageImage1 { get; set; }
        public string PageImage2 { get; set; }
        public string PageImage3 { get; set; }
        public string PageImage4 { get; set; }
        public string PageImage5 { get; set; }
        public string PageImage6 { get; set; }
        public string PageImage7 { get; set; }
        public string PageImage8 { get; set; }
        public string AboutText { get; set; }
        public string LogoImage { get; set; }
        public string BreadCrumColor { get; set; }
        public string LookBookColor { get; set; }
        public string LookBookBorderColor { get; set; }
        public string ShopTheCollectionTextColor { get; set; }
    }
}
