//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoughaibandco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGiftCard
    {
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ToEmail { get; set; }
        public string ToFirstName { get; set; }
        public string ToLastName { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeliver { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string ToPhoneNo { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Referenceid { get; set; }
    }
}
