//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoughaibandco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDeliveryDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string PrimaryAddress { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string SecondaryAddress { get; set; }
        public string PrimaryPhoneNo { get; set; }
        public string SecondaryPhoneNo { get; set; }
        public string AdditionalInformation { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryMessage { get; set; }
    }
}
