//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoughaibandco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> OrderQy { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<long> ProductId { get; set; }
    }
}
