//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoughaibandco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> CollectionId { get; set; }
        public string Description { get; set; }
        public string Materials { get; set; }
        public Nullable<decimal> GoldWeight { get; set; }
        public Nullable<decimal> Round { get; set; }
        public Nullable<decimal> Marquis { get; set; }
        public Nullable<decimal> Ruby { get; set; }
        public Nullable<decimal> Sapphire { get; set; }
        public Nullable<decimal> Emerald { get; set; }
        public Nullable<decimal> Fancy { get; set; }
        public Nullable<decimal> Princes { get; set; }
        public Nullable<decimal> Baguette { get; set; }
        public Nullable<decimal> Triangle { get; set; }
        public Nullable<decimal> Pear { get; set; }
        public Nullable<decimal> black { get; set; }
        public Nullable<decimal> semiprecious { get; set; }
        public Nullable<decimal> diamond { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceDiscounted { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<decimal> Priceold { get; set; }
        public Nullable<decimal> Brown { get; set; }
        public Nullable<decimal> SP { get; set; }
        public bool IsParent { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int SequenceNumber { get; set; }
        public string ReferenceNO { get; set; }
    }
}
