//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoughaibandco.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zoughaibandco_DBEntities : DbContext
    {
        public Zoughaibandco_DBEntities()
            : base("name=Zoughaibandco_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Career> Careers { get; set; }
        public virtual DbSet<StoreAddress> StoreAddresses { get; set; }
        public virtual DbSet<StoreLocator> StoreLocators { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ProductWishList> ProductWishLists { get; set; }
        public virtual DbSet<ProductCartDetail> ProductCartDetails { get; set; }
        public virtual DbSet<ProductCart> ProductCarts { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<EGiftCard> EGiftCards { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDeliveryDetail> OrderDeliveryDetails { get; set; }
        public virtual DbSet<ProductCartDetailsGuest> ProductCartDetailsGuests { get; set; }
        public virtual DbSet<ProductCartGuest> ProductCartGuests { get; set; }
        public virtual DbSet<ProductWishListGuest> ProductWishListGuests { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
